### ISSUE TITLE
Windows Leak Error

### ISSUE THREAD

**Issue by Singwai** [douglasjunior/android-simple-tooltip#31]
```bash
01-19 14:49:36.767 29017-29017/se.yo.android.bloglovin.dev E/WindowManager: android.view.WindowLeaked: Activity se.yo.android.bloglovincore.view.activity.FeedActivity has leaked window android.widget.PopupWindow$PopupDecorView{92cb78f V.E...... .......D 0,0-1120,412} that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:418)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at android.widget.PopupWindow.invokePopup(PopupWindow.java:1378)
        at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1154)
        at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1121)
        at io.github.douglasjunior.androidSimpleTooltip.SimpleTooltip$1.run(SimpleTooltip.java:171)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

**Comment by Singwai** [comment]
I believe the library is trying to draw the tooltip when the activity is destroy.

**Comment by douglasjunior** [comment]
Thanks for the feedback!

Which version are you using? Did you check if it is not one of the [known issues](https://github.com/douglasjunior/android-simple-tooltip#known-issues)?

**Comment by Singwai** [comment]
Thank you for the quick response. In fact, it is one of the known issue. Will fix that accordingly.

 Thanks.

**Comment by douglasjunior** [comment]
@Singwai, this exception may be caused by many reasons. But this should not be a problem as it does not cause crashes in the app.

Make a test:

1. Open a Activity.
2. Open a Tooltip.
3. Without closing the Tooltip, press device Back Button to close the Activity.
