### ISSUE TITLE
onDismiss() not working 

### ISSUE THREAD

**Issue by arslanyasin** [douglasjunior/android-simple-tooltip#32]
hello!
i m calling tooltip.build().dismiss(); in my onBackpress() method but it gives me exception 
my dismiss code is..
```java
 if (tooltip != null && tooltip.isShowing()) {
        tooltip.dismiss();
    }
```
and exception is 
```java
java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
                                                                        at android.view.ViewGroup.addViewInner(ViewGroup.java:3582)
                                                                        at android.view.ViewGroup.addView(ViewGroup.java:3435)
                                                                        at android.view.ViewGroup.addView(ViewGroup.java:3380)
                                                                        at android.view.ViewGroup.addView(ViewGroup.java:3356)
                                                                        at io.github.douglasjunior.androidSimpleTooltip.SimpleTooltip.configContentView(SimpleTooltip.java:265)
                                                                        at io.github.douglasjunior.androidSimpleTooltip.SimpleTooltip.init(SimpleTooltip.java:148)
                                                                        at io.github.douglasjunior.androidSimpleTooltip.SimpleTooltip.<init>(SimpleTooltip.java:143)
                                                                        at io.github.douglasjunior.androidSimpleTooltip.SimpleTooltip.<init>(SimpleTooltip.java:67)
                                                                        at io.github.douglasjunior.androidSimpleTooltip.SimpleTooltip$Builder.build(SimpleTooltip.java:605)
                                                                        at com.sysops.thenx.fragment.WorkOut.onDetach(WorkOut.java:1438)
                                                                        at android.support.v4.app.Fragment.performDetach(Fragment.java:2436)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1443)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1523)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1598)
                                                                        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2145)
                                                                        at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2092)
                                                                        at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:822)
                                                                        at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:775)
                                                                        at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:178)
                                                                        at com.sysops.thenx.activity.MainActivity.onBackPressed(MainActivity.java:162)
                                                                        at android.app.Activity.onKeyUp(Activity.java:2231)
                                                                        at android.view.KeyEvent.dispatch(KeyEvent.java:2706)
                                                                        at android.app.Activity.dispatchKeyEvent(Activity.java:2475)
                                                                        at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:547)
                                                                        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
                                                                        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:319)
                                                                        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2019)
                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4133)
                                                                        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4107)
                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3613)
                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3663)
                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3632)
                                                                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3739)
                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3640)
                                                                        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3796)
                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3613)
                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3663)
                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3632)
                                                                        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3640)
                                                                        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3613)
                                                                        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3663)
                                                                        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3632)
                                                                        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3772)
                                                                        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3934)
                                                                        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2019)
                                                                        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1713)
                                                                    	at android.view.inputmethod.InputMethodM
```

please help me out thank you

**Comment by douglasjunior** [comment]
Hi @ArslanYasin , thanks for create a new Issue!

As I sayed in other issue, you need to handle the `onBackPressed` like this:

```java
@Override
public void onBackPressed() {
    if (tooltip != null && tooltip.isShowing()) {
        tooltip.dismiss();
    } else {
        super.onBackPressed();
    }
}
```

If the exceptions its happen, its because the Activity is closing before the Tooltip. The Tooltip is base on PopupWindow, see the [known-issues](https://github.com/douglasjunior/android-simple-tooltip#known-issues) to undestand this problem. Note that the known-issues dont crash your app, is just a logcat message.

The problem related in #22 is caused for others reasons.

**Comment by arslanyasin** [comment]
@douglasjunior as you said i call super.onDetach() after dismiss i am using onDetach() because i use fragment instead of activity and use tooltip.build().dismiss() but it give me again same exception

**Comment by douglasjunior** [comment]
You cant call `tooltip.build().dismiss()` directly. In this way you are building a new Tooltip, and not closing the existing Tooltip.

You need to do something like this:

```java
class YourFragment {

    private SimpleTooltip tooltip;

    onClickButton() {
          tooltip = new SimpleTooltip.Builder(this)
          .anchorView(yourView)
          .text("Texto do Tooltip")
          .gravity(Gravity.END)
          .animated(true)
          .transparentOverlay(false)
          .build();
          tooltip.show(); 
   }

    @Override
    public void onDatach() {
        if (tooltip != null && tooltip.isShowing()) {
            tooltip.dismiss();
        }
        super.onDatach();
    }
}
```

If you want to use `onBackPressed`in fragment, look this http://stackoverflow.com/questions/5448653/how-to-implement-onbackpressed-in-fragments

Why you are using `onDatach`? You tried to use the `onDestroy`? http://stackoverflow.com/questions/26369905/activitys-ondestroy-fragments-ondestroyview-set-null-practices

**Comment by arslanyasin** [comment]
but when i code like this
```java
   private SimpleTooltip tooltip;

    onClickButton() {
          tooltip = new SimpleTooltip.Builder(this)
          .anchorView(yourView)
          .text("Texto do Tooltip")
          .gravity(Gravity.END)
          .animated(true)
          .transparentOverlay(false)
          .build();
          tooltip.show(); 
   }
```
`tooltip = new SimpleTooltip.Builder(this)` gives me error incompatible types
Required SimpleToolip.Simpletooltip
Found    SimpleTooltip.SimpleTooltip.Builder

and wehn i use SimpleToolip.Simpletooltip not allow me also gives error

**Comment by douglasjunior** [comment]
Wrong:
```java
tooltip = new SimpleTooltip.Builder(this);
```

Correct:
```java
tooltip = new SimpleTooltip.Builder(this).build();
```

This is a design pattern called [Builder](https://en.wikipedia.org/wiki/Builder_pattern).

**Comment by arslanyasin** [comment]
but if i use 
tooltip = new SimpleTooltip.Builder(this).build();

then not allow me tooltip.contentview(id) and other functions...

**Comment by arslanyasin** [comment]
its done
Thank you so much for your guideline really appreciated.. :)

**Comment by douglasjunior** [comment]
Great! Your welcome. 😃
